sarey_erp/sarey_erp/Models/detalleInventario.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace sarey_erp.Models
{
    public class detalleInventario
    {
        public string idFaena { get; set; }
        public float cantidad { get; set; }
        public string nombreItem { get; set; }

        public static void agregarDetalle(detalleInventario detalle) 
        {
            SqlConnection cnx = conexion.crearConexion();
            if (detalleInventario.verificarSiExiste(detalle.idFaena, detalle.nombreItem))
            {
                SqlCommand cmd_ = new SqlCommand();
                cmd_.Connection = cnx;
                cmd_.CommandText = "UPDATE detalle_inventario SET cantidad=@cantidad"
                  + " WHERE id_faena='" + detalle.idFaena + "' AND nombre_item='" + detalle.nombreItem + "'";

                double cantidad_anterior = detalleInventario.obtenerCantidadItem(detalle.idFaena, detalle.nombreItem);

                cmd_.Parameters.Add("@cantidad", SqlDbType.Float).Value = detalle.cantidad + cantidad_anterior;
                cmd_.ExecuteNonQuery();
            }
            else
            {
                SqlCommand cmd = new SqlCommand();
                cmd.Connection = cnx;
                cmd.CommandText = "insert into detalle_inventario(id_faena,cantidad,nombre_item) values('"
                   + detalle.idFaena + "','"
                   + detalle.cantidad + "','"
                   + detalle.nombreItem + "')";
                cmd.CommandType = CommandType.Text;
                cmd.ExecuteNonQuery();

            }
        }

        public static detalleInventario obtenerItem(string nombreItem, string faena) 
        {
            detalleInventario retorno = new detalleInventario();

            SqlConnection cnx = conexion.crearConexion();

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cnx;
            cmd.CommandText = "SELECT * FROM detalle_inventario WHERE nombre_item=@nombreItem AND id_faena=@faena";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Add("@nombreItem", SqlDbType.VarChar).Value=nombreItem;
            cmd.Parameters.Add("@faena", SqlDbType.VarChar).Value = faena;

            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                detalleInventario nueva = new detalleInventario();

                retorno.idFaena = (string)dr["id_faena"];
                retorno.cantidad = float.Parse(dr["cantidad"].ToString());
                retorno.nombreItem = (string)dr["nombre_item"];
            }

            cnx.Close();

            return retorno;
        }

        public static List<detalleInventario> obtenerTodos()
        {
            List<detalleInventario> retorno = new List<detalleInventario>();

            SqlConnection cnx = conexion.crearConexion();

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cnx;
            cmd.CommandText = "SELECT * from detalle_inventario ORDER BY id_faena ASC";
            cmd.CommandType = CommandType.Text;
            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                detalleInventario nueva = new detalleInventario();

                nueva.idFaena = (string)dr["id_faena"];
                nueva.cantidad = float.Parse(dr["cantidad"].ToString());
                nueva.nombreItem = (string)dr["nombre_item"];

                retorno.Add(nueva);
            }

            cnx.Close();

            return retorno;
        }

        public static List<detalleInventario> obtenerTodosFaena(string faena)
        {
            List<detalleInventario> retorno = new List<detalleInventario>();

            SqlConnection cnx = conexion.crearConexion();

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cnx;
            cmd.CommandText = "SELECT * from detalle_inventario WHERE id_faena=@idFaena ORDER BY id_faena ASC";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Add("@idFaena", SqlDbType.VarChar).Value = faena;

            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                detalleInventario nueva = new detalleInventario();

                nueva.idFaena = (string)dr["id_faena"];
                nueva.cantidad = float.Parse(dr["cantidad"].ToString());
                nueva.nombreItem = (string)dr["nombre_item"];

                retorno.Add(nueva);
            }

            cnx.Close();

            return retorno;
        }

        public static List<detalleInventario> obtenerTodosFaenaItem(string faena, string item)
        {
            List<detalleInventario> retorno = new List<detalleInventario>();

            SqlConnection cnx = conexion.crearConexion();

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cnx;
            cmd.CommandText = "SELECT * from detalle_inventario WHERE id_faena=@idFaena AND nombre_item=@item ORDER BY id_faena ASC";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Add("@idFaena", SqlDbType.VarChar).Value = faena;
            cmd.Parameters.Add("@item", SqlDbType.VarChar).Value = item;

            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                detalleInventario nueva = new detalleInventario();

                nueva.idFaena = (string)dr["id_faena"];
                nueva.cantidad = float.Parse(dr["cantidad"].ToString());
                nueva.nombreItem = (string)dr["nombre_item"];

                retorno.Add(nueva);
            }

            cnx.Close();

            return retorno;
        }

        public static List<detalleInventario> obtenerTodosItem(string item)
        {
            List<detalleInventario> retorno = new List<detalleInventario>();

            SqlConnection cnx = conexion.crearConexion();

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cnx;
            cmd.CommandText = "SELECT * from detalle_inventario WHERE nombre_item=@item ORDER BY id_faena ASC";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Add("@item", SqlDbType.VarChar).Value = item;

            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                detalleInventario nueva = new detalleInventario();

                nueva.idFaena = (string)dr["id_faena"];
                nueva.cantidad = float.Parse(dr["cantidad"].ToString());
                nueva.nombreItem = (string)dr["nombre_item"];

                retorno.Add(nueva);
            }

            cnx.Close();

            return retorno;
        }

        public static List<string> obtenerFaenas()
        {
            List<string> retorno = new List<string>();

            SqlConnection cnx = conexion.crearConexion();

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cnx;
            cmd.CommandText = "SELECT DISTINCT id_faena from detalle_inventario ORDER BY id_faena ASC";
            cmd.CommandType = CommandType.Text;

            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                retorno.Add((string)dr["id_faena"]);
            }

            cnx.Close();

            return retorno;
        }

        public static List<string> obtenerFaenasItem(string item)
        {
            List<string> retorno = new List<string>();

            SqlConnection cnx = conexion.crearConexion();

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cnx;
            cmd.CommandText = "SELECT DISTINCT id_faena from detalle_inventario WHERE nombre_item=@item ORDER BY id_faena ASC";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Add("@item", SqlDbType.VarChar).Value = item;

            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                retorno.Add((string)dr["id_faena"]);
            }

            cnx.Close();

            return retorno;
        }

        public static List<string> obtenerItems()
        {
            List<string> retorno = new List<string>();

            SqlConnection cnx = conexion.crearConexion();

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cnx;
            cmd.CommandText = "SELECT DISTINCT nombre_item from detalle_inventario ORDER BY nombre_item ASC";
            cmd.CommandType = CommandType.Text;

            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                retorno.Add((string)dr["nombre_item"]);
            }

            cnx.Close();

            return retorno;
        }

        public static List<string> obtenerItemsFaena(string faena)
        {
            List<string> retorno = new List<string>();

            SqlConnection cnx = conexion.crearConexion();

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cnx;
            cmd.CommandText = "SELECT DISTINCT nombre_item from detalle_inventario WHERE id_faena=@faena ORDER BY nombre_item ASC";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Add("@faena", SqlDbType.VarChar).Value = faena;

            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                retorno.Add((string)dr["nombre_item"]);
            }

            cnx.Close();

            return retorno;
        }

        public static double obtenerCantidadItem(string faena, string item) {

            SqlConnection cnx = conexion.crearConexion();

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = cnx;
            cmd.CommandText = "SELECT cantidad from detalle_inventario WHERE id_faena='" + faena + "' AND nombre_item='" + item + "'";
            cmd.CommandType = CommandType.Text;           

sarey_erp/sarey_erp/Controllers/detalleInventarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using sarey_erp.Models;
using System.Data;
using System.Data.SqlClient;

namespace sarey_erp.Controllers
{
    public class detalleInventarioController : Controller
    {
        //
        // GET: /detalleInventario/

        public ActionResult Index()
        {
            List<detalleInventario> lista = detalleInventario.obtenerTodos();

            ViewBag.Faenas = detalleInventario.obtenerFaenas();
            ViewBag.Items = detalleInventario.obtenerItems();

            ViewBag.Faena = "";
            ViewBag.Item = "";

            return View(lista);
        }

        public ActionResult IndexFiltro(string faena, string item)
        {
            List<detalleInventario> lista  = new List<detalleInventario>();
            if (item == null)
            {
                lista = detalleInventario.obtenerTodosFaena(faena);
                ViewBag.Faena = faena;
                ViewBag.Item = "";

                ViewBag.Faenas = detalleInventario.obtenerFaenas();
                ViewBag.Items = detalleInventario.obtenerItemsFaena(faena);
            }
            else if (faena == null)
            {
                lista = detalleInventario.obtenerTodosItem(item);
                ViewBag.Faena = "";
                ViewBag.Item = item;

                ViewBag.Faenas = detalleInventario.obtenerFaenasItem(item);
                ViewBag.Items = detalleInventario.obtenerItems();
            }
            else if (item == null && faena == null)
            {
                RedirectToAction("Index");
            }
            else
            {
                lista = detalleInventario.obtenerTodosFaenaItem(faena, item);
                ViewBag.Faena = faena;
                ViewBag.Item = item;

                ViewBag.Faenas = detalleInventario.obtenerFaenasItem(item);
                ViewBag.Items = detalleInventario.obtenerItemsFaena(faena);
            }

            return View("Index",lista);
        }

        public ActionResult realizarTraspaso(FormCollection form)
        {
            string item = (string)form["item"];            
            string antiguaFaena = (string)form["anteriorFaena"];
            double cantidadExistenteItem = Convert.ToDouble((string)form["cantidadExistenteItem"]);
            string nuevaFaena = (string)form["faena"];
            double cantidadTraspasar = Convert.ToDouble((string)form["cantidadTraspasar"]);

            double diferencia = 0;

            SqlConnection cnx = conexion.crearConexion();

            if (detalleInventario.verificarSiExiste(nuevaFaena, item))
            {
                SqlCommand cmd_ = new SqlCommand();
                cmd_.Connection = cnx;
                cmd_.CommandText = "UPDATE detalle_inventario SET cantidad=@cantidad"
                  + " WHERE id_faena='" + nuevaFaena + "' AND nombre_item='" + item + "'";

                double cantidad_anterior = detalleInventario.obtenerCantidadItem(nuevaFaena, item);

                cmd_.Parameters.Add("@cantidad", SqlDbType.Float).Value = cantidadTraspasar + cantidad_anterior;
                cmd_.ExecuteNonQuery();
            }
            else {
               
                SqlCommand cmd = new SqlCommand();
                cmd.Connection = cnx;
                cmd.CommandText = "insert into detalle_inventario(id_faena,cantidad,nombre_item) values('"
                   + nuevaFaena + "','"
                   + cantidadTraspasar + "','"
                   + item + "')";
                cmd.CommandType = CommandType.Text;
                cmd.ExecuteNonQuery();
               
            }
            diferencia = (cantidadExistenteItem - cantidadTraspasar);
            if (diferencia == 0)
            {
                SqlCommand cmd_ = new SqlCommand();
                cmd_.Connection = cnx;                          
                cmd_.CommandText = "DELETE FROM detalle_inventario WHERE (id_faena='" + antiguaFaena + "' AND nombre_item='" + item + "')";
                cmd_.CommandType = CommandType.Text;
                cmd_.ExecuteNonQuery();

            }
            else
            {

                SqlCommand cmd_ = new SqlCommand();
                cmd_.Connection = cnx;
                cmd_.CommandText = "UPDATE detalle_inventario SET cantidad=@cantidad "
                  + " WHERE id_faena='" + antiguaFaena + "' AND nombre_item='" + item + "'";

                cmd_.Parameters.Add("@cantidad", SqlDbType.Float).Value = diferencia;
                cmd_.ExecuteNonQuery();

            }
                        
            cnx.Close();

            return RedirectToAction("Index");
        }

        public ActionResult Traspaso(string nombreItem, string idFaena)
        {
            //ViewData["items"] = detalleInventario.obtenerTodos(); 
            ViewBag.item = nombreItem;
            ViewBag.faena = idFaena;
            detalleInventario detalleInv = detalleInventario.obtenerItem(nombreItem, idFaena);
            ViewBag.cantidadItem = detalleInv.cantidad;

            ViewData["faenas"] = faena.obtenerTodas();
            return View();
        }             
    }
}

sarey_erp/sarey_erp/Views/detalleInventario/Index.cshtml
@model List<sarey_erp.Models.detalleInventario>
@{
    ViewBag.Title = "Detalle de Inventario";
    WebGrid grid = new WebGrid(Model, rowsPerPage: 10);
}

<div class="content-wrapper">
    <br />
    <div class="page-header">
        <h2 class="text-center">Detalle de Inventario</h2>
    </div>
    <div class="content">
        <div class="table-responsive">
            @grid.GetHtml(
            columns: grid.Columns(
                    grid.Column("idFaena",
                    header: string.Format("Faena o Bodega {0}", grid.SortColumn == "idFaena" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted"),

                    grid.Column("nombreItem",
                    header: string.Format("Ítem {0}", grid.SortColumn == "nombreItem" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted"),

                    grid.Column("cantidad",
                    header: string.Format("Cantidad {0}", grid.SortColumn == "cantidad" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted"),
                    grid.Column("",
                    header: "Cambiar Ubicación",
                    format: @<text>
                    @if (Session["rol"]!=null && (Session["rol"].ToString().Equals("existencias") || Session["rol"].ToString().Equals("admin")))
                    {
                        <a href="@Url.Action("Traspaso", "detalleInventario", new { nombreItem = item.nombreItem, idFaena = item.idFaena })"><span class='glyphicon glyphicon-transfer text-primary'></span></a>
                    }
                    </text>)
            ), 
            tableStyle: "table table-hover table-bordered table-striped", footerStyle: "pagination")
        </div>
        <div class="col-sm-10 col-sm-offset-1">
            <h3>Filtros:</h3>
            <div class="col-sm-6">
                <label class="control-label">Faena o Bodega</label>
                <select class="form-control" id="selectFaena">
                    <option value="todos">Todos</option>
                    @{
                        List<string> faenas = ViewBag.Faenas;
                        foreach (string faena in faenas)
                        {
                            if (ViewBag.Faena.Equals(faena))
                            {
                                <option value="@faena" selected>@faena</option>
                            }
                            else
                            {
                                <option value="@faena">@faena</option>
                            }
                        }
                    }
                </select>
            </div>
            <div class="col-sm-6">
                <label class="control-label">Ítem</label>
                <select class="form-control" id="selectItem">
                    <option value="todos">Todos</option>
                    @{
                        List<string> items = ViewBag.Items;
                        foreach (string item in items)
                        {
                            if (ViewBag.Item.Equals(item))
                            {
                                <option value="@item" selected>@item</option>
                            }
                            else
                            {
                                <option value="@item">@item</option>
                            }
                        }
                    }
                </select>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">

        function aplicarFiltro()
        {
            faena = $("#selectFaena").val();
            item = $("#selectItem").val();

            url = "";

            if (faena != "todos" && item != "todos") {
                url = "/detalleInventario/IndexFiltro?faena=" + faena + "&item=" + item;
            }
            else if (faena != "todos")
            {
                url = "/detalleInventario/IndexFiltro?faena=" + faena;
            }
            else if (item != "todos") {
                url = "/detalleInventario/IndexFiltro?item=" + item;
            }
            else {
                url = "/detalleInventario/Index";
            }

            console.log(url);
            window.location = url;
        }

        $("#selectFaena").change(function () {
            aplicarFiltro();
        });

        $("#selectItem").change(function () {
            aplicarFiltro();
        });

    </script>
}

sarey_erp/sarey_erp/Views/detalleInventario/Traspaso.cshtml
@{
    ViewBag.Title = "Traspaso";
}


<div class="content-wrapper">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">           
            <h3 class="text-center">Realizar Traspaso de Items entre Faenas</h3>
            <br />                
                <form action="@Url.Action("realizarTraspaso","detalleInventario")" role="form" method="post" enctype="multipart/form-data" onsubmit="return validarFormulario();">
                    <div class="form-group">
                        <label class="control-label">Item</label>
                        <input type="text" name="item" id="item" value="@ViewBag.item" readonly />
                        <input type="hidden" name="anteriorFaena" value="@ViewBag.faena" />
                    </div>
                    <div class="form-group">
                        <label class="control-label"> Cantidad de Item en Faena</label>
                        <input type="text" name="cantidadExistenteItem" id="cantidadExistenteItem" value="@ViewBag.cantidadItem" readonly />
                    </div>
                    <br /><br />
                    <div class="form-group">
                        <label class="control-label">Seleccione Faena a traspasar</label>
                        <select class="form-control faena" name="faena" id="faena">
                            <option></option>
                            @foreach (sarey_erp.Models.faena Faena in (List<sarey_erp.Models.faena>)ViewData["faenas"])
                            {
                                if (!@Faena.nombre.Equals(@ViewBag.faena)) { 
                                    <option value="@Faena.nombre">@Faena.nombre</option>
                                }
                            }
                        </select>
                    </div>

                    <div class="form-group">
                        <label class="control-label"> Cantidad a traspasar</label>
                        <input type="number" min="1" name="cantidadTraspasar" id="cantidadTraspasar" required />
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Traspasar</button>
                    </div>

                </form>

</div>
        </div>
</div>



@section scripts{
    <script type="text/javascript">

        function cambiarItem(elemento) {
            var valores = elemento.value.split("/");
            var faena = valores[0];
            var item = valores[1];
            var cantidad = valores[2];
            $("#cantidadExistenteItem").val(cantidad);
        }

        function validarFormulario() {            

            var retorno = true;
            var cantidadExistente = parseInt($("#cantidadExistenteItem").val());
            
            var cantidadTraspasar = parseInt($("#cantidadTraspasar").val());
            var selectItem=$("#item").val();
            var selectFaena=$("#faena").val();
            
            if (selectFaena == "") {
                alert("Debe seleccionar Faena");
                retorno = false;
            } else if (selectItem = "") {
                alert("Debe seleccionar Item");
                retorno = false;
            }

            if (cantidadTraspasar > cantidadExistente) {
                alert("No puede ingresar una cantidad de items Mayor a la existente en la faena");
                retorno = false;
            }
            return retorno;
        }

</script>
}